### ISSUE TITLE
`gm -version || convert -version` failed

### ISSUE THREAD

**Issue by hoanguyen311** [twolfson/gmsmith#10]
I get this problem when running `npm isntall` which trigger `gm -version || convert -version`

node -v
v5.8.0

npm -v
3.7.3

**Comment by twolfson** [comment]
That error message means neither GraphicsMagick nor ImageMagick is installed. Those are dependencies of this package. They are documented here:

https://github.com/twolfson/gmsmith/tree/1.1.0#requirements
