### ISSUE TITLE
update version in npm to 5.0

### ISSUE THREAD

**Issue by evilebottnawi** [twolfson/gmsmith#6]

**Comment by twolfson** [comment]
The current version of `gmsmith` is `0.5.0`. Can you provide more information on this issue?

**Comment by evilebottnawi** [comment]
@twolfson in https://gemnasium.com Latest
![screenshot from 2015-09-15 10 53 16](https://cloud.githubusercontent.com/assets/4567934/9870830/032c31c4-5b98-11e5-9143-127c1fb5d603.png)
 version show 0.4.2

**Comment by twolfson** [comment]
I am not sure where Gemnasium is getting its information. The latest version on `npm` is `0.5.0` and there were even releases up to `0.4.5` after `0.4.2` =/

https://www.npmjs.com/package/gmsmith

![screen shot 2015-09-15 at 11 49 21 am](https://cloud.githubusercontent.com/assets/902488/9883461/d6e0098a-5b9f-11e5-8c34-c9096c3f0012.png)

```bash
$ npm info gmsmith
// ...
  versions:
// ..
     '0.4.0',
     '0.4.1',
     '0.4.2',
     '0.4.3',
     '0.4.4',
     '0.4.5',
     '0.5.0' ],
// ...
  version: '0.5.0',
```
