### ISSUE TITLE
Update gm dependency because of security issue

### ISSUE THREAD

**Issue by danez** [twolfson/gmsmith#7]
https://nodesecurity.io/advisories/54

**Comment by twolfson** [comment]
We aren't using `gm.compare` in this repo so thankfully this isn't time sensitive. Would you be interested in submitting a PR?

**Comment by danez** [comment]
Maybe you want to enable http://greenkeeper.io/ which would automatically create PR for new versions of dependencies.

**Comment by twolfson** [comment]
Unfortunately that's impractical for me as I maintain too many repos. I would end up landing/releasing 10 PRs a day and need to deal with any possible regressions introduced by said PRs. Letting code stay stable seems much more practical.

**Comment by twolfson** [comment]
This has been resolved in `1.1.0` via @danez' work in #9
